# package developed by @alihaider78222

name: appearance
description: "Flutter package to implement Light, Dark and Sytem Theme mode, and persist it on restart of app."
version: 0.0.1
homepage: https://github.com/alihaider78222/appearance
issue_tracker: https://github.com/alihaider78222/appearance/issues
repository: https://github.com/alihaider78222/appearance

platforms:
  android:
  ios:
  web:

screenshots:
  - description: 'Material App Light and Dark mode.'
    path: screenshots/appearance.png
  - description: 'Cupertino App Light and Dark mode.'
    path: screenshots/appearance_2.png

topics:
  - appearance
  - theme
  - light-mode
  - dark-mode


environment:
  sdk: '>=3.2.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: '>=2.1.1 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
